### ISSUE TITLE
Critical File not getting any CSS

### ISSUE THREAD

**Issue by JakeHenshall** [mistakster/postcss-pipeline-webpack-plugin#23]
Hey,

This is exactly what I'm looking for :).

I'm using this in my Webpack Config and it is generating the critical file and also the map, but when I add in the comments where I want the scss to be extracted nothing seems to enter that file.

1. Can you use this with SCSS or do it have the be pure CSS.
2. Can you Generate Multiple critical files from the comment code e.g home.critical.css / single.critical.css 

Would you like to me post the webpack.config.js here?

Thanks, Jake.

**Comment by mistakster** [comment]
Hi, Jake.

This webpack plugin works with any PostCSS plugin. I gave extracting critical styles only as an example. You can do anything that PostCSS with its plugins can do. It just helps to organise the processing pipelines.

As for your questions, PostCSS can process SCSS files with [relevant parser](https://github.com/postcss/postcss-scss) and you can setup as many pipelines (plugin instances) as you need to generate multiple critical files. Sorry, I can’t help you with your configurations any further.

V
