### ISSUE TITLE
How change full name of ctitical part?

### ISSUE THREAD

**Issue by romanlex** [mistakster/postcss-pipeline-webpack-plugin#41]
Can I change fullname of critical file? Not only suffix
I want set name for critical as `critical.[contenthash:12].css`
Name for prod files as `app.395ff6e90875.critical.css` is very strange
contenthash from filename relation to app.css not critical.css
When app.css will be changed the hash will also be changed but content of critical part maybe not

**Comment by mistakster** [comment]
I do believe you can use any other webpack plugin to rename generated assets. For example, https://github.com/sun1l/rename-output-webpack-plugin

**Comment by romanlex** [comment]
@mistakster thx but all this plugins use entry for rename
In this case critical css is not entry, I don't known output name of app.css for use this plugins

**Comment by mistakster** [comment]
@romanlex, hi! Maybe I’m too late, but I released version 5.1.0 which fits into your use case. Please see details in https://github.com/mistakster/postcss-pipeline-webpack-plugin/issues/57#issuecomment-508193537
