### ISSUE TITLE
Why critical css doesn't remove from styles?

### ISSUE THREAD

**Issue by romanlex** [mistakster/postcss-pipeline-webpack-plugin#42]
In my case critical styles not removed from main bundle of style
I need add `PostCssPipelineWebpackPlugin` with `criticalSplit` and `output: rest`?

**Comment by adamrights** [comment]
The issue is that postcss-critical-split does remove the critical styles, but when run through postcss-pipeline-webpack-plugin this does not occur.

**Comment by mrnocreativity** [comment]
This could be down to the settings used @adamrights. Did you validate the correct split-options were passed? Depending on the split-options, either the original css, the rest-css or the critical-css is returned ;)

**Comment by KhoaSydney** [comment]
I have the same issue in which the critical css does not get removed from the original css.

**Comment by mistakster** [comment]
@KhoaSydney, please, could you provide the configuration which doesn’t work?

**Comment by KhoaSydney** [comment]
Hi @mistakster ,
The configuration is similar to the example provided on here. I do get the critical css extracted out into a file but the extracted content is still in the original files.

**Comment by mistakster** [comment]
Hello guys! Let me share my configuration which works perfectly: https://github.com/mistakster/postcss-pipeline-webpack-plugin/tree/master/examples 

I can build [styles.critical.css](https://github.com/mistakster/postcss-pipeline-webpack-plugin/blob/master/examples/dest/styles.critical.css) and [styles.rest.css](https://github.com/mistakster/postcss-pipeline-webpack-plugin/blob/master/examples/dest/styles.rest.css) alongside with complete [styles.css](https://github.com/mistakster/postcss-pipeline-webpack-plugin/blob/master/examples/dest/styles.css).

I hope my example helps you.

**Comment by mrnocreativity** [comment]
Thanks for sharing @mistakster :)
