### ISSUE TITLE
Assets don't appear in manifest

### ISSUE THREAD

**Issue by vstoyanoff** [mistakster/postcss-pipeline-webpack-plugin#71]
Hi,

I am using this plugin in order to extract the critical css and generate the rest css files, but when I am processing the assets with the webpack-assets-manifest plugin, these files don't appear in the assets. The only place I could find references to the new files is in the `manifest.stats` but it is not sufficient for me to use. Why don't they appear in the assets array?

**Comment by mistakster** [comment]
Hi Veselin! It might it's a matter of the order of the plugins. Can you provide your minimal configuration to reproduce the problem?

**Comment by vstoyanoff** [comment]
Hey. That was quick! Thanks!
Here is how the plugins are used:
`
       new MiniCssExtractPlugin({
            esModule: true,
            chunkFilename: "web/css/[name].[contenthash].css",
        }),
        new PostCssPipelineWebpackPlugin({
            processor: postcss([
                criticalSplit({
                    output: criticalSplit.output_types.CRITICAL_CSS,
                }),
            ]),
            suffix: "critical",
        }),
        new PostCssPipelineWebpackPlugin({
            processor: postcss([
                criticalSplit({
                    output: criticalSplit.output_types.REST_CSS,
                }),
            ]),
            suffix: "rest",
            predicate: (name) => /.+(?<!critical)\.css$/.test(name), // don't process just-generated critical css
        }),
        new WebpackAssetsManifest({
          // Provide a list of entrypoints in the output
          entrypoints: true,
          // Arbitrary name
          output: fileName,
          // Append the publicPath to the assets so we don't have to do it in python
          publicPath: true,
          // Ensure webpack-dev-server doesn't eat this file
          writeToDisk: true,
        })
 `

**Comment by vstoyanoff** [comment]
I am using a custom plugin that extends the webpack-assets-manifest and I hook into the plugin hooks that are exposed, but the new assets are not present

**Comment by mistakster** [comment]
Okay. Let me check the config you provided, and I will back to you later.

**Comment by vstoyanoff** [comment]
Any luck with it? I am not sure if this is coming from this plugin or from the webpack-assets-manifest plugin. I tried to figure out the source code of the webpack-assets-manifest, but it is difficult for me to see whether there is something that I might use. I saw the source code of this plugin as well and from what I saw I think I understand that the new assets are added as a RawSource to the webpack manifest.

**Comment by mistakster** [comment]
Hi! Sorry for the delay. I've found that my plugin is not fully compatible with webpack v5. With `webpack@4` and `webpack-assets-manifest@4` I got the following manifest file:

```json
{
  "entrypoints": {
    "main": {
      "assets": {
        "css": [
          "styles.css"
        ],
        "js": [
          "main.js"
        ]
      }
    }
  },
  "main.css": "styles.css",
  "main.js": "main.js",
  "styles.critical.css": "styles.critical.css",
  "styles.critical.min.css": "styles.critical.min.css",
  "styles.critical.min.css.map": "styles.critical.min.css.map",
  "styles.rest.css": "styles.rest.css",
  "styles.rest.min.css": "styles.rest.min.css",
  "styles.rest.min.css.map": "styles.rest.min.css.map"
}
```

I will fix these compatibility issues and release the fixed version later today.

Thanks for the report.

**Comment by mistakster** [comment]
Hi @vstoyanoff

I've just release v6.0.0. It's fully compatible with webpack 5 now. I hope this release fixes your problem. Please, check it out and let me know it something is still broken for you.

**Comment by vstoyanoff** [comment]
Hey @mistakster.

Sorry for the delay. Happy new year! Thank you for the support and the fix. It works fine now!

**Comment by mistakster** [comment]
@vstoyanoff, thank you! Happy new year! 😁🎉
